### ISSUE TITLE
[1.20.1][Bug]: Log Spam from Distant Horizons

### ISSUE THREAD

**Issue by Reshy** [someaddons/structureessentials#1]
### Describe the bug you're experiencing

The mod causes any virtual chunks generated by Distant Horizons to spit out long dense errors that quickly balloon to gigabytes in size if left unchecked.

Log size after less than 5 minutes:
![image](https://github.com/user-attachments/assets/d25a8c54-b322-4105-bbbb-b21f930c09a6)

Log Size in a larger modpack that's run for about an hour:
![image](https://github.com/user-attachments/assets/9359b771-8626-440e-9f35-5b5de43891f4)

### Reproducability

Install both Structure Essentials, Distant Horizons, and any structure adding more (for consistency)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://pastebin.com/z5sZQxdW

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by someaddons** [comment]
Those logs only happen when structure essentials prevented a structure placement from crashing your game. So it simply displays the issue and prevents the crash but is not at fault for any of the issues

**Comment by Reshy** [comment]
Removing the mod doesn't result in any crashing.

**Comment by someaddons** [comment]
then distant horizons hides the error themselves, should ask them to not error the structures then
